# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('widgets', '0004_auto_20171007_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='Angles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('angle', models.FloatField(db_index=True, max_length=250)),
                ('widgets', models.ManyToManyField(db_index=True, related_name='angles', to='widgets.Widget')),
            ],
        ),
    ]
