# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0003_auto_20171008_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='angle',
            name='widgets',
            field=models.ManyToManyField(db_index=True, related_name='angles', to='widgets.Widget'),
        ),
    ]
