# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 16:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0006_auto_20171031_1600'),
        ('recommendations', '0004_auto_20171008_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='Angle2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('angle', models.FloatField(db_index=True, max_length=250)),
                ('widgets', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movieB', to='widgets.Widget')),
            ],
        ),
    ]
