# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-07 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('shape', models.CharField(blank=True, max_length=250, null=True)),
                ('height', models.IntegerField(db_index=True, default=0)),
                ('width', models.IntegerField(db_index=True, default=0)),
                ('color', models.CharField(max_length=250)),
                ('image', models.ImageField(blank=True, null=True, upload_to='widgets')),
            ],
        ),
    ]
