# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-07 18:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0002_auto_20171007_1837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='widget',
            old_name='diliked',
            new_name='disliked',
        ),
    ]
