# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-07 18:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('widgets', '0003_auto_20171007_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='user',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='widget',
        ),
        migrations.RemoveField(
            model_name='widget',
            name='disliked',
        ),
        migrations.AddField(
            model_name='widget',
            name='disliked',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='widget',
            name='liked',
        ),
        migrations.AddField(
            model_name='widget',
            name='liked',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
