# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0004_auto_20171007_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='widget',
            name='catgory',
            field=models.ManyToManyField(blank=True, null=True, to='widgets.Category'),
        ),
    ]
