# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0005_auto_20171031_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='catgory',
            field=models.ManyToManyField(blank=True, to='widgets.Category'),
        ),
    ]
