# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0006_auto_20171031_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='widget',
            name='color',
        ),
        migrations.RemoveField(
            model_name='widget',
            name='height',
        ),
        migrations.RemoveField(
            model_name='widget',
            name='shape',
        ),
        migrations.RemoveField(
            model_name='widget',
            name='width',
        ),
        migrations.AddField(
            model_name='widget',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
