# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0007_auto_20171031_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='borrowed',
            field=models.IntegerField(default=0),
        ),
    ]
