# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0009_rent'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='returned',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
